import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Lyric Guesser",
  description: "Generated by me :)",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        <div className="grid h-screen grid-rows-[auto,1fr]">
          <div className="h-20 w-full border-b"></div>
          <main className="h-full overflow-y-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
